------------------ DROP USER - START ----------------------
DROP USER SAMPLE_DB_OWNER CASCADE;
DROP TABLESPACE SAMPLE_TABLESPACE INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE SAMPLE_TABLESPACE_TMP INCLUDING CONTENTS AND DATAFILES;
------------------ DROP USER - END ------------------------

--------------- CREATE OBJECTS - START --------------------
CREATE USER SAMPLE_DB_OWNER IDENTIFIED BY "password";
GRANT ALL PRIVILEGES TO SAMPLE_DB_OWNER;

CREATE TABLESPACE SAMPLE_TABLESPACE
DATAFILE 'sample_tablespace.dat'
SIZE 10M REUSE AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE SAMPLE_TABLESPACE_TMP
TEMPFILE 'sample_tablespace_temp.dat'
SIZE 10M REUSE AUTOEXTEND ON;

GRANT CONNECT TO SAMPLE_DB_OWNER;
GRANT CONNECT, RESOURCE, DBA TO SAMPLE_DB_OWNER;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO SAMPLE_DB_OWNER;
GRANT UNLIMITED TABLESPACE TO SAMPLE_DB_OWNER;
--------------- CREATE OBJECTS - END ------------------------
